language: php
php:
#  - 7.0
  - 5.6
  - 5.5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-utils php5-curl

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer -o dump-autoload
  - mkdir -p ./build/

script:
  - find . -path "./src/*.php" -exec php -l {} \;
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php vendor/bin/pdepend --jdepend-chart=./build/jdepend-chart.svg --jdepend-xml=./build/jdepend.xml --overview-pyramid=./build/jdepend-pyramid.svg --summary-xml=./build/pdepend-summary.xml --coverage-report=./build/clover.xml --suffix=php --ignore=**/vendor/**,**/tests/** ./src/
  - php vendor/bin/phploc --names="*.php" --count-tests --exclude="vendor" --log-csv="./build/phploc.csv" --log-xml="./build/phploc.xml" --progress ./src ./tests
  - php vendor/bin/phpcpd --names="*.php" --log-pmd="./build/phpcpd.xml" --progress ./src/
  - php vendor/bin/phpmd ./src/ xml cleancode,codesize,controversial,design,naming,unusedcode --reportfile ./build/phpmd.xml --minimumpriority 1 || true
  - php vendor/bin/phpcs -np --report=checkstyle --report-checkstyle=./build/checkstyle.xml --standard=PSR2 --ignore=**/vendor/**,**/tests/** --extensions=php ./src ./tests || true


after_script:
  - php vendor/bin/coveralls
  - CODECLIMATE_REPO_TOKEN=06624a7693cc9f1d51ec4c84e563dea6f26bdfde7206567d331adbfd96a52605 ./vendor/bin/test-reporter --coverage-report="./build/clover.xml"
